<?php

namespace test\GaddourBundle\Repository;

/**
 * ReponseEtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseEtudiantRepository extends \Doctrine\ORM\EntityRepository
{
}
